# Use an official Node runtime as a parent image
FROM node:16-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json AND package-lock.json to /app
COPY ./package.json ./
# COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the client source code to /app
COPY . .

# Expose port 3000
# EXPOSE 3000

# Start the client
CMD ["npm", "start"]